'use client'

import { useState } from 'react'

/**
 * A brand mark that removes itself if the file is missing.
 *
 * The icon set is generated by `scripts/build-icons.mjs` from `simple-icons`,
 * and not every product on the CV has a mark published there — Micronaut,
 * ActiveMQ and Liquibase come and go between releases. Without this, a missing
 * file renders the browser's broken-image glyph in the middle of a skills row,
 * which is worse than showing no icon at all.
 */
export default function SkillIcon({
  file,
  size = 17,
}: {
  file: string
  size?: number
}) {
  const [broken, setBroken] = useState(false)
  if (broken) return null

  return (
    <img
      src={`/icons/${file}`}
      alt=""
      width={size}
      height={size}
      loading="lazy"
      decoding="async"
      onError={() => setBroken(true)}
    />
  )
}
